version: "3.6"
services:
  nostr-rs-relay:
    image: scsibug/nostr-rs-relay
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nostr-rs-relay/data:/usr/src/app/db:Z
      - ./docker/nostr-rs-relay/config.toml:/usr/src/app/config.toml:ro,Z
    container_name: nostr-rs-relay
  noscl-reader:
    build:
      context: docker/noscl-reader
      dockerfile: Dockerfile
    volumes:
      - ./docker/noscl-reader/config.json:/root/.config/nostr/config.json
      - ./docker/noscl-reader/src:/root/src
    container_name: noscl-reader
  noscl-writer:
    build:
      context: docker/noscl-writer
      dockerfile: Dockerfile
    volumes:
      - ./docker/noscl-writer/config.json:/root/.config/nostr/config.json
      - ./docker/noscl-writer/src:/root/src
    container_name: noscl-writer
  verimod:
    build:
      context: docker/verimod
      dockerfile: Dockerfile
    volumes:
      - ./docker/verimod/src:/usr/src/verimod
    container_name: verimod
    ports:
      - "8000:8000"
  filter-server:
    build:
      context: docker/filter-server
      dockerfile: Dockerfile
    volumes:
      - ./docker/filter-server/src:/usr/src/filter-server/src
      - ./docker/filter-server/config.json:/usr/src/filter-server/config.json
    container_name: filter-server
    command: python3 /usr/src/filter-server/src/server.py --config /usr/src/filter-server/config.json
  admin:
    build:
      context: docker/admin
      dockerfile: Dockerfile
    volumes:
      - ./docker/admin/src:/usr/src/admin
    container_name: admin
